### ISSUE TITLE
No homepage pages are working after upgrading to v6.2.5

### ISSUE THREAD

**Issue by chrisvidal** [artistro08/tailor-starter#67] opened 2023-02-15 05:27 UTC
I have 2 test website and no home pages are working after upgrading to v6.2.5.

its an error 404 apparently

**Comment by artistro08** [comment] 2023-02-15 10:35
I just tested on an upgrade install and it looks like it's working on my end. The main issue that I did run into when setting a homepage is that you should have a slug. 

Could you check and see if the slug is set? The theme uses that to make sure it detects the right page.

**Comment by chrisvidal** [comment] 2023-02-15 11:08
yes it has a slug

<img width="1482" alt="image" src="https://user-images.githubusercontent.com/2263496/219011221-55727cef-2949-44a0-b0c0-8fe6e8465255.png">

**Comment by artistro08** [comment] 2023-02-15 11:10
Try saving it again and see if the issue persists.

**Comment by chrisvidal** [comment] 2023-02-15 11:31
I did save a few times already and didn't solve it.
I will delete the page data and create it again and see

**Comment by artistro08** [comment] 2023-02-15 11:45
Since you've been around for a while, you may be running to the bug I had but could never fix. I haven't been able to reproduce it consistently either, so it makes it a pain in the butt. I'll come up with more solutions once I am able to pinpoint the issue.

**Comment by artistro08** [comment] 2023-02-15 21:42
I also, just tested it in a long standing environment to see if I could reproduce as well. No dice unfortunately.

**Comment by artistro08** [comment] 2023-02-16 02:53
Closing as you said it was working correctly now in #66

**Comment by chrisvidal** [comment] 2023-02-16 03:28
it works on a new fresh install but not the upgraded existing version.
I have an error 404

**Comment by artistro08** [comment] 2023-02-16 03:36
You could put  `{{ dd(settings.homepage is empty) }}` in the `index.htm` template at various places to see why it returns empty.

**Comment by artistro08** [comment] 2023-02-16 03:40
also, if you could zip your theme and child theme folders and send it to me, I could figure out the problem as well.

**Comment by artistro08** [comment] 2023-02-18 03:27
@chrisvidal did you ever figure this out?

**Closed** 2023-02-18 13:40 UTC
